apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-from-api
  namespace: scholarship-platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: scholarship-platform-redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: scholarship-platform-api
      ports:
        - protocol: TCP
          port: 6379
